### ISSUE TITLE
Add Additional Logic Around Skipping

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#4]
**Is your feature request related to a problem? Please describe.**
Can we add logic to skip a file that doesn't match, if its in another acceptable format? For instance, I go to convert things to h264, but if they are in h265, good enough!

**Describe the solution you'd like**
Add option in config to skip if file has the specified alternate format.

**Comment by Wolveix** [comment]
This would actually be a bit of a pain to implement since it would require the implementation and acceptance of multiple codecs, which requires rewriting quite a few things. There are probably simpler ways than I'm thinking to achieve the same end result, however, I don't believe that they would be substantially beneficial.

In your use case, I would suggest building the file list based off of the file container alone as opposed to the video codec. H264 and H265 will both almost always be within an MKV or MP4 container. Support for this has been added in [Plexus v0.9.65](https://github.com/Wolveix/Plexus/commit/7e6c37c8e62fa336480a20af481054a21c39f0f0)
